// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_busola_screen_init(void)
{
    ui_busola = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_busola, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_busola, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_busola, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imunghi = lv_img_create(ui_busola);
    lv_img_set_src(ui_imunghi, &ui_img_1955478482);
    lv_obj_set_width(ui_imunghi, LV_SIZE_CONTENT);   /// 334
    lv_obj_set_height(ui_imunghi, LV_SIZE_CONTENT);    /// 334
    lv_obj_set_x(ui_imunghi, -2);
    lv_obj_set_y(ui_imunghi, 0);
    lv_obj_set_align(ui_imunghi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imunghi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imunghi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_imunghi, 168, 168);
    lv_img_set_angle(ui_imunghi, 7);
    lv_img_set_zoom(ui_imunghi, 190);

    ui_imsageata = lv_img_create(ui_busola);
    lv_img_set_src(ui_imsageata, &ui_img_1717721989);
    lv_obj_set_width(ui_imsageata, LV_SIZE_CONTENT);   /// 166
    lv_obj_set_height(ui_imsageata, LV_SIZE_CONTENT);    /// 166
    lv_obj_set_x(ui_imsageata, -1);
    lv_obj_set_y(ui_imsageata, 0);
    lv_obj_set_align(ui_imsageata, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_imsageata, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_imsageata, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_imsageata, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imsageata, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imsageata, 194);

    ui_unghi = lv_label_create(ui_busola);
    lv_obj_set_width(ui_unghi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_unghi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_unghi, 32);
    lv_obj_set_y(ui_unghi, 1);
    lv_obj_set_align(ui_unghi, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_unghi, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_unghi, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_unghi, "300°");
    lv_obj_set_style_text_color(ui_unghi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unghi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_unghi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unghi, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_directie = lv_label_create(ui_busola);
    lv_obj_set_width(ui_directie, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_directie, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_directie, -28);
    lv_obj_set_y(ui_directie, 1);
    lv_obj_set_align(ui_directie, LV_ALIGN_CENTER);
    lv_label_set_text(ui_directie, "NE");
    lv_obj_set_style_text_color(ui_directie, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_directie, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_directie, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_directie, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_busola, ui_event_busola, LV_EVENT_ALL, NULL);

}
