// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ecranbluetooth_screen_init(void)
{
    ui_ecranbluetooth = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ecranbluetooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ecranbluetooth, lv_color_hex(0x293039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ecranbluetooth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numedispozitiv = lv_label_create(ui_ecranbluetooth);
    lv_obj_set_width(ui_numedispozitiv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_numedispozitiv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_numedispozitiv, 0);
    lv_obj_set_y(ui_numedispozitiv, -52);
    lv_obj_set_align(ui_numedispozitiv, LV_ALIGN_CENTER);
    lv_label_set_text(ui_numedispozitiv, "S10+_SM975F");
    lv_obj_set_style_text_color(ui_numedispozitiv, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_numedispozitiv, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_numedispozitiv, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_numedispozitiv, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dorestesaseconecteze = lv_label_create(ui_ecranbluetooth);
    lv_obj_set_width(ui_dorestesaseconecteze, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dorestesaseconecteze, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dorestesaseconecteze, 2);
    lv_obj_set_y(ui_dorestesaseconecteze, -15);
    lv_obj_set_align(ui_dorestesaseconecteze, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dorestesaseconecteze, "Doreste sa se conecteze");
    lv_obj_set_style_text_color(ui_dorestesaseconecteze, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dorestesaseconecteze, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_dorestesaseconecteze, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dorestesaseconecteze, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refuza = lv_btn_create(ui_ecranbluetooth);
    lv_obj_set_width(ui_refuza, 92);
    lv_obj_set_height(ui_refuza, 38);
    lv_obj_set_x(ui_refuza, -51);
    lv_obj_set_y(ui_refuza, 35);
    lv_obj_set_align(ui_refuza, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_refuza, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_refuza, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_refuza, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_refuza, lv_color_hex(0xF70201), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_refuza, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_refuza, lv_color_hex(0xF60000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_refuza, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refuzal = lv_label_create(ui_refuza);
    lv_obj_set_width(ui_refuzal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_refuzal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_refuzal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_refuzal, "Refuza");
    lv_obj_set_style_text_font(ui_refuzal, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accepta = lv_btn_create(ui_ecranbluetooth);
    lv_obj_set_width(ui_accepta, 92);
    lv_obj_set_height(ui_accepta, 38);
    lv_obj_set_x(ui_accepta, 51);
    lv_obj_set_y(ui_accepta, 35);
    lv_obj_set_align(ui_accepta, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_accepta, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_accepta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_accepta, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_accepta, lv_color_hex(0x08DA8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_accepta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_accepta, lv_color_hex(0x08DA8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_accepta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_acceptal = lv_label_create(ui_accepta);
    lv_obj_set_width(ui_acceptal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_acceptal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_acceptal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_acceptal, "Accepta");
    lv_obj_set_style_text_color(ui_acceptal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_acceptal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_acceptal, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
