// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ecranceas2_screen_init(void)
{
    ui_ecranceas2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ecranceas2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ecranceas2, lv_color_hex(0x293039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ecranceas2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ora = lv_obj_create(ui_ecranceas2);
    lv_obj_remove_style_all(ui_ora);
    lv_obj_set_width(ui_ora, 176);
    lv_obj_set_height(ui_ora, 44);
    lv_obj_set_x(ui_ora, 0);
    lv_obj_set_y(ui_ora, -41);
    lv_obj_set_align(ui_ora, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ora, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_ora, lv_color_hex(0x00AEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ora, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ora, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ora, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ora1 = lv_label_create(ui_ora);
    lv_obj_set_width(ui_ora1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ora1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ora1, -69);
    lv_obj_set_y(ui_ora1, 0);
    lv_obj_set_align(ui_ora1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ora1, "0");

    ui_ora2 = lv_label_create(ui_ora);
    lv_obj_set_width(ui_ora2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ora2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ora2, -45);
    lv_obj_set_y(ui_ora2, 0);
    lv_obj_set_align(ui_ora2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ora2, "9");

    ui_douap1 = lv_label_create(ui_ora);
    lv_obj_set_width(ui_douap1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_douap1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_douap1, -28);
    lv_obj_set_y(ui_douap1, -3);
    lv_obj_set_align(ui_douap1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_douap1, ":");

    ui_min1 = lv_label_create(ui_ora);
    lv_obj_set_width(ui_min1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min1, -12);
    lv_obj_set_y(ui_min1, 0);
    lv_obj_set_align(ui_min1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_min1, "0");

    ui_min2 = lv_label_create(ui_ora);
    lv_obj_set_width(ui_min2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min2, 12);
    lv_obj_set_y(ui_min2, 0);
    lv_obj_set_align(ui_min2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_min2, "0");

    ui_douap2 = lv_label_create(ui_ora);
    lv_obj_set_width(ui_douap2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_douap2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_douap2, 29);
    lv_obj_set_y(ui_douap2, -3);
    lv_obj_set_align(ui_douap2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_douap2, ":");

    ui_sec0 = lv_label_create(ui_ora);
    lv_obj_set_width(ui_sec0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec0, 45);
    lv_obj_set_y(ui_sec0, 0);
    lv_obj_set_align(ui_sec0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sec0, "0");

    ui_sec1 = lv_label_create(ui_ora);
    lv_obj_set_width(ui_sec1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec1, 69);
    lv_obj_set_y(ui_sec1, 0);
    lv_obj_set_align(ui_sec1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sec1, "0");

    ui_baterie = lv_obj_create(ui_ecranceas2);
    lv_obj_remove_style_all(ui_baterie);
    lv_obj_set_width(ui_baterie, 83);
    lv_obj_set_height(ui_baterie, 20);
    lv_obj_set_x(ui_baterie, 1);
    lv_obj_set_y(ui_baterie, -99);
    lv_obj_set_align(ui_baterie, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_baterie, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_procent = lv_bar_create(ui_baterie);
    lv_bar_set_value(ui_procent, 75, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_procent, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_procent, 27);
    lv_obj_set_height(ui_procent, 14);
    lv_obj_set_x(ui_procent, -22);
    lv_obj_set_y(ui_procent, 0);
    lv_obj_set_align(ui_procent, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_procent, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_procent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_procent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_procent, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_procent, lv_color_hex(0x0EDB8A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_procent, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_nr = lv_label_create(ui_baterie);
    lv_obj_set_width(ui_nr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nr, 8);
    lv_obj_set_y(ui_nr, 0);
    lv_obj_set_align(ui_nr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nr, "100");
    lv_obj_set_style_text_color(ui_nr, lv_color_hex(0x0EDB8A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nr, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_procent1 = lv_label_create(ui_baterie);
    lv_obj_set_width(ui_procent1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_procent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_procent1, 30);
    lv_obj_set_y(ui_procent1, 0);
    lv_obj_set_align(ui_procent1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_procent1, "%");
    lv_obj_set_style_text_color(ui_procent1, lv_color_hex(0x0EDB8A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_procent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_procent1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_data = lv_obj_create(ui_ecranceas2);
    lv_obj_remove_style_all(ui_data);
    lv_obj_set_width(ui_data, 161);
    lv_obj_set_height(ui_data, 17);
    lv_obj_set_x(ui_data, 0);
    lv_obj_set_y(ui_data, -73);
    lv_obj_set_align(ui_data, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_data, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_data, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zisapt = lv_label_create(ui_data);
    lv_obj_set_width(ui_zisapt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zisapt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zisapt, -55);
    lv_obj_set_y(ui_zisapt, 0);
    lv_obj_set_align(ui_zisapt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zisapt, "WED");
    lv_obj_set_style_text_color(ui_zisapt, lv_color_hex(0x00AEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zisapt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zi = lv_label_create(ui_data);
    lv_obj_set_width(ui_zi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zi, -20);
    lv_obj_set_y(ui_zi, 0);
    lv_obj_set_align(ui_zi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zi, "1");
    lv_obj_set_style_text_color(ui_zi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_luna = lv_label_create(ui_data);
    lv_obj_set_width(ui_luna, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_luna, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_luna, 13);
    lv_obj_set_y(ui_luna, 0);
    lv_obj_set_align(ui_luna, LV_ALIGN_CENTER);
    lv_label_set_text(ui_luna, "IAN");
    lv_obj_set_style_text_color(ui_luna, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_luna, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_an = lv_label_create(ui_data);
    lv_obj_set_width(ui_an, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_an, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_an, 56);
    lv_obj_set_y(ui_an, 0);
    lv_obj_set_align(ui_an, LV_ALIGN_CENTER);
    lv_label_set_text(ui_an, "2024");
    lv_obj_set_style_text_color(ui_an, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_an, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contpasi = lv_obj_create(ui_ecranceas2);
    lv_obj_remove_style_all(ui_contpasi);
    lv_obj_set_width(ui_contpasi, 107);
    lv_obj_set_height(ui_contpasi, 36);
    lv_obj_set_x(ui_contpasi, -62);
    lv_obj_set_y(ui_contpasi, 1);
    lv_obj_set_align(ui_contpasi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_contpasi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_pasi = lv_img_create(ui_contpasi);
    lv_img_set_src(ui_pasi, &ui_img_634488199);
    lv_obj_set_width(ui_pasi, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_pasi, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_pasi, -20);
    lv_obj_set_y(ui_pasi, 0);
    lv_obj_set_align(ui_pasi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pasi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pasi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_pasi, 115);

    ui_nrpasi = lv_label_create(ui_contpasi);
    lv_obj_set_width(ui_nrpasi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nrpasi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nrpasi, 21);
    lv_obj_set_y(ui_nrpasi, 0);
    lv_obj_set_align(ui_nrpasi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nrpasi, "1.14");
    lv_obj_set_style_text_color(ui_nrpasi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nrpasi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_nrpasi, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nrpasi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_contpasi);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 41);
    lv_obj_set_y(ui_Label9, 0);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "k");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contpuls = lv_obj_create(ui_ecranceas2);
    lv_obj_remove_style_all(ui_contpuls);
    lv_obj_set_width(ui_contpuls, 101);
    lv_obj_set_height(ui_contpuls, 28);
    lv_obj_set_x(ui_contpuls, 55);
    lv_obj_set_y(ui_contpuls, 1);
    lv_obj_set_align(ui_contpuls, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_contpuls, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_bpm = lv_img_create(ui_contpuls);
    lv_img_set_src(ui_bpm, &ui_img_53009338);
    lv_obj_set_width(ui_bpm, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_bpm, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_bpm, -31);
    lv_obj_set_y(ui_bpm, 0);
    lv_obj_set_align(ui_bpm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bpm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bpm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bpm, 185);

    ui_puls = lv_label_create(ui_contpuls);
    lv_obj_set_width(ui_puls, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_puls, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_puls, 1);
    lv_obj_set_y(ui_puls, 0);
    lv_obj_set_align(ui_puls, LV_ALIGN_CENTER);
    lv_label_set_text(ui_puls, "109");
    lv_obj_set_style_text_color(ui_puls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_puls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_puls, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_puls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ubpm = lv_label_create(ui_contpuls);
    lv_obj_set_width(ui_ubpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ubpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ubpm, 34);
    lv_obj_set_y(ui_ubpm, 0);
    lv_obj_set_align(ui_ubpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ubpm, "BPM");
    lv_obj_set_style_text_color(ui_ubpm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ubpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contdistanta = lv_obj_create(ui_ecranceas2);
    lv_obj_remove_style_all(ui_contdistanta);
    lv_obj_set_width(ui_contdistanta, 102);
    lv_obj_set_height(ui_contdistanta, 44);
    lv_obj_set_x(ui_contdistanta, -54);
    lv_obj_set_y(ui_contdistanta, 46);
    lv_obj_set_align(ui_contdistanta, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_contdistanta, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_distanta = lv_img_create(ui_contdistanta);
    lv_img_set_src(ui_distanta, &ui_img_distanta_png);
    lv_obj_set_width(ui_distanta, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_distanta, LV_SIZE_CONTENT);    /// 93
    lv_obj_set_x(ui_distanta, -24);
    lv_obj_set_y(ui_distanta, 0);
    lv_obj_set_align(ui_distanta, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_distanta, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_distanta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_distanta, 95);

    ui_nrdistanta = lv_label_create(ui_contdistanta);
    lv_obj_set_width(ui_nrdistanta, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nrdistanta, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nrdistanta, 10);
    lv_obj_set_y(ui_nrdistanta, -2);
    lv_obj_set_align(ui_nrdistanta, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nrdistanta, "2.46");
    lv_obj_set_style_text_color(ui_nrdistanta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nrdistanta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_nrdistanta, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nrdistanta, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmdisanta = lv_label_create(ui_contdistanta);
    lv_obj_set_width(ui_kmdisanta, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmdisanta, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmdisanta, 41);
    lv_obj_set_y(ui_kmdisanta, -2);
    lv_obj_set_align(ui_kmdisanta, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmdisanta, "km");
    lv_obj_set_style_text_color(ui_kmdisanta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kmdisanta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contox = lv_obj_create(ui_ecranceas2);
    lv_obj_remove_style_all(ui_contox);
    lv_obj_set_width(ui_contox, 78);
    lv_obj_set_height(ui_contox, 35);
    lv_obj_set_x(ui_contox, 57);
    lv_obj_set_y(ui_contox, 41);
    lv_obj_set_align(ui_contox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_contox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_oxigen = lv_img_create(ui_contox);
    lv_img_set_src(ui_oxigen, &ui_img_1191119266);
    lv_obj_set_width(ui_oxigen, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_oxigen, LV_SIZE_CONTENT);    /// 78
    lv_obj_set_x(ui_oxigen, -26);
    lv_obj_set_y(ui_oxigen, 0);
    lv_obj_set_align(ui_oxigen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_oxigen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_oxigen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_oxigen, 105);

    ui_nrox = lv_label_create(ui_contox);
    lv_obj_set_width(ui_nrox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nrox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nrox, 3);
    lv_obj_set_y(ui_nrox, 3);
    lv_obj_set_align(ui_nrox, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nrox, "100");
    lv_obj_set_style_text_color(ui_nrox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nrox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_nrox, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nrox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_procentox = lv_label_create(ui_contox);
    lv_obj_set_width(ui_procentox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_procentox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_procentox, 25);
    lv_obj_set_y(ui_procentox, 3);
    lv_obj_set_align(ui_procentox, LV_ALIGN_CENTER);
    lv_label_set_text(ui_procentox, "%");
    lv_obj_set_style_text_color(ui_procentox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_procentox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_procentox, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contcal = lv_obj_create(ui_ecranceas2);
    lv_obj_remove_style_all(ui_contcal);
    lv_obj_set_width(ui_contcal, 107);
    lv_obj_set_height(ui_contcal, 34);
    lv_obj_set_x(ui_contcal, 0);
    lv_obj_set_y(ui_contcal, 83);
    lv_obj_set_align(ui_contcal, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_contcal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_cal = lv_img_create(ui_contcal);
    lv_img_set_src(ui_cal, &ui_img_1673018674);
    lv_obj_set_width(ui_cal, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_cal, LV_SIZE_CONTENT);    /// 74
    lv_obj_set_x(ui_cal, -37);
    lv_obj_set_y(ui_cal, 0);
    lv_obj_set_align(ui_cal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_cal, 120);

    ui_nrcal = lv_label_create(ui_contcal);
    lv_obj_set_width(ui_nrcal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nrcal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nrcal, 0);
    lv_obj_set_y(ui_nrcal, 4);
    lv_obj_set_align(ui_nrcal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nrcal, "1000");
    lv_obj_set_style_text_color(ui_nrcal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nrcal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_nrcal, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nrcal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kcal = lv_label_create(ui_contcal);
    lv_obj_set_width(ui_kcal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kcal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kcal, 36);
    lv_obj_set_y(ui_kcal, 4);
    lv_obj_set_align(ui_kcal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kcal, "KCal");
    lv_obj_set_style_text_color(ui_kcal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kcal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ecranceas2, ui_event_ecranceas2, LV_EVENT_ALL, NULL);

}
