// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ecranalerte_screen_init(void)
{
    ui_ecranalerte = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ecranalerte, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ecranalerte, lv_color_hex(0x293039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ecranalerte, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Textalerta = lv_label_create(ui_ecranalerte);
    lv_obj_set_width(ui_Textalerta, 169);
    lv_obj_set_height(ui_Textalerta, 165);
    lv_obj_set_x(ui_Textalerta, 3);
    lv_obj_set_y(ui_Textalerta, 45);
    lv_obj_set_align(ui_Textalerta, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Textalerta, "Este timpul sa iti iei pastilele ");
    lv_obj_set_style_text_color(ui_Textalerta, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Textalerta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Textalerta, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Textalerta, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

}
