// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ecranhealth_screen_init(void)
{
    ui_ecranhealth = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ecranhealth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ecranhealth, lv_color_hex(0x293039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ecranhealth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inima = lv_img_create(ui_ecranhealth);
    lv_img_set_src(ui_inima, &ui_img_53009338);
    lv_obj_set_width(ui_inima, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_inima, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_inima, -51);
    lv_obj_set_y(ui_inima, -21);
    lv_obj_set_align(ui_inima, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_inima, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_inima, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_inima, 300);

    ui_Arc1 = lv_arc_create(ui_ecranhealth);
    lv_obj_set_width(ui_Arc1, 80);
    lv_obj_set_height(ui_Arc1, 80);
    lv_obj_set_x(ui_Arc1, -52);
    lv_obj_set_y(ui_Arc1, -22);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_Arc1, 0, 220);
    lv_arc_set_value(ui_Arc1, 85);
    lv_arc_set_bg_angles(ui_Arc1, 90, 449);
    lv_obj_set_style_arc_width(ui_Arc1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Arc1, -10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Arc1, -10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Arc1, -10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Arc1, -10, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_ecranhealth);
    lv_obj_set_width(ui_Arc2, 80);
    lv_obj_set_height(ui_Arc2, 80);
    lv_obj_set_x(ui_Arc2, 54);
    lv_obj_set_y(ui_Arc2, -22);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_Arc2, 95);
    lv_arc_set_bg_angles(ui_Arc2, 90, 449);
    lv_obj_set_style_arc_width(ui_Arc2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x00CEFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Arc2, -10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Arc2, -10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Arc2, -10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Arc2, -10, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_butonmasurare = lv_btn_create(ui_ecranhealth);
    lv_obj_set_width(ui_butonmasurare, 135);
    lv_obj_set_height(ui_butonmasurare, 34);
    lv_obj_set_x(ui_butonmasurare, 0);
    lv_obj_set_y(ui_butonmasurare, 77);
    lv_obj_set_align(ui_butonmasurare, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_butonmasurare, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_butonmasurare, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_butonmasurare, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_butonmasurare, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_butonmasurare, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_butonmasurare, lv_color_hex(0x00CEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_butonmasurare, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_butonmasurare, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_butonmasurare, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_butonmasurare, lv_color_hex(0x293039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_butonmasurare, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_butonmasurare, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_butonmasurare, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_butonmasurare, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_butonmasurare, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Masurare = lv_label_create(ui_butonmasurare);
    lv_obj_set_width(ui_Masurare, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Masurare, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Masurare, 0);
    lv_obj_set_y(ui_Masurare, 11);
    lv_obj_set_align(ui_Masurare, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Masurare, "Masurare\n");
    lv_obj_set_style_text_color(ui_Masurare, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Masurare, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Masurare, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BPM = lv_label_create(ui_ecranhealth);
    lv_obj_set_width(ui_BPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BPM, -68);
    lv_obj_set_y(ui_BPM, 39);
    lv_obj_set_align(ui_BPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BPM, "BPM:");
    lv_obj_set_style_text_color(ui_BPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BPM, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numarpuls = lv_label_create(ui_ecranhealth);
    lv_obj_set_width(ui_numarpuls, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_numarpuls, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_numarpuls, -28);
    lv_obj_set_y(ui_numarpuls, 39);
    lv_obj_set_align(ui_numarpuls, LV_ALIGN_CENTER);
    lv_label_set_text(ui_numarpuls, "120");
    lv_obj_set_style_text_color(ui_numarpuls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_numarpuls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_numarpuls, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spo2 = lv_label_create(ui_ecranhealth);
    lv_obj_set_width(ui_Spo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Spo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Spo2, 32);
    lv_obj_set_y(ui_Spo2, 39);
    lv_obj_set_align(ui_Spo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Spo2, "Spo2:");
    lv_obj_set_style_text_color(ui_Spo2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Spo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spo2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spo2value = lv_label_create(ui_ecranhealth);
    lv_obj_set_width(ui_Spo2value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Spo2value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Spo2value, 79);
    lv_obj_set_y(ui_Spo2value, 39);
    lv_obj_set_align(ui_Spo2value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Spo2value, "100%");
    lv_obj_set_style_text_color(ui_Spo2value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Spo2value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spo2value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sanatate = lv_textarea_create(ui_ecranhealth);
    lv_obj_set_width(ui_Sanatate, 243);
    lv_obj_set_height(ui_Sanatate, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Sanatate, 0);
    lv_obj_set_y(ui_Sanatate, -98);
    lv_obj_set_align(ui_Sanatate, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_Sanatate, "Sanatate");
    lv_textarea_set_placeholder_text(ui_Sanatate, "Placeholder...");
    lv_textarea_set_one_line(ui_Sanatate, true);
    lv_obj_set_style_text_color(ui_Sanatate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Sanatate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Sanatate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Sanatate, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Sanatate, lv_color_hex(0x181C20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sanatate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Sanatate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Sanatate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Sanatate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Sanatate, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Sanatate, 8, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_imaginespo2 = lv_img_create(ui_ecranhealth);
    lv_img_set_src(ui_imaginespo2, &ui_img_1191119266);
    lv_obj_set_width(ui_imaginespo2, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_imaginespo2, LV_SIZE_CONTENT);    /// 78
    lv_obj_set_x(ui_imaginespo2, 54);
    lv_obj_set_y(ui_imaginespo2, -23);
    lv_obj_set_align(ui_imaginespo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imaginespo2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imaginespo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imaginespo2, 165);

    lv_obj_add_event_cb(ui_butonmasurare, ui_event_butonmasurare, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ecranhealth, ui_event_ecranhealth, LV_EVENT_ALL, NULL);

}
