// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "C:\Users\pc\Desktop\SquareLine_Project\libraries\lvgl\lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ecranceas2
void ui_ecranceas2_screen_init(void);
void ui_event_ecranceas2(lv_event_t * e);
extern lv_obj_t * ui_ecranceas2;
extern lv_obj_t * ui_ora;
extern lv_obj_t * ui_ora1;
extern lv_obj_t * ui_ora2;
extern lv_obj_t * ui_douap1;
extern lv_obj_t * ui_min1;
extern lv_obj_t * ui_min2;
extern lv_obj_t * ui_douap2;
extern lv_obj_t * ui_sec0;
extern lv_obj_t * ui_sec1;
extern lv_obj_t * ui_baterie;
extern lv_obj_t * ui_procent;
extern lv_obj_t * ui_nr;
extern lv_obj_t * ui_procent1;
extern lv_obj_t * ui_data;
extern lv_obj_t * ui_zisapt;
extern lv_obj_t * ui_zi;
extern lv_obj_t * ui_luna;
extern lv_obj_t * ui_an;
extern lv_obj_t * ui_contpasi;
extern lv_obj_t * ui_pasi;
extern lv_obj_t * ui_nrpasi;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_contpuls;
extern lv_obj_t * ui_bpm;
extern lv_obj_t * ui_puls;
extern lv_obj_t * ui_ubpm;
extern lv_obj_t * ui_contdistanta;
extern lv_obj_t * ui_distanta;
extern lv_obj_t * ui_nrdistanta;
extern lv_obj_t * ui_kmdisanta;
extern lv_obj_t * ui_contox;
extern lv_obj_t * ui_oxigen;
extern lv_obj_t * ui_nrox;
extern lv_obj_t * ui_procentox;
extern lv_obj_t * ui_contcal;
extern lv_obj_t * ui_cal;
extern lv_obj_t * ui_nrcal;
extern lv_obj_t * ui_kcal;
// SCREEN: ui_busola
void ui_busola_screen_init(void);
void ui_event_busola(lv_event_t * e);
extern lv_obj_t * ui_busola;
extern lv_obj_t * ui_imunghi;
extern lv_obj_t * ui_imsageata;
extern lv_obj_t * ui_unghi;
extern lv_obj_t * ui_directie;
// SCREEN: ui_ecranhealth
void ui_ecranhealth_screen_init(void);
void ui_event_ecranhealth(lv_event_t * e);
extern lv_obj_t * ui_ecranhealth;
extern lv_obj_t * ui_inima;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Arc2;
void ui_event_butonmasurare(lv_event_t * e);
extern lv_obj_t * ui_butonmasurare;
extern lv_obj_t * ui_Masurare;
extern lv_obj_t * ui_BPM;
extern lv_obj_t * ui_numarpuls;
extern lv_obj_t * ui_Spo2;
extern lv_obj_t * ui_Spo2value;
extern lv_obj_t * ui_Sanatate;
extern lv_obj_t * ui_imaginespo2;
// SCREEN: ui_ecransetari
void ui_ecransetari_screen_init(void);
void ui_event_ecransetari(lv_event_t * e);
extern lv_obj_t * ui_ecransetari;
extern lv_obj_t * ui_setariscris;
void ui_event_butonwifi(lv_event_t * e);
extern lv_obj_t * ui_butonwifi;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_switchwifi;
void ui_event_butonluminozitate(lv_event_t * e);
extern lv_obj_t * ui_butonluminozitate;
extern lv_obj_t * ui_luminoz;
void ui_event_butondespre(lv_event_t * e);
extern lv_obj_t * ui_butondespre;
extern lv_obj_t * ui_despre;
extern lv_obj_t * ui_butonbluetooth;
extern lv_obj_t * ui_bluetooth;
extern lv_obj_t * ui_switchble;
// SCREEN: ui_ecranlumina
void ui_ecranlumina_screen_init(void);
void ui_event_ecranlumina(lv_event_t * e);
extern lv_obj_t * ui_ecranlumina;
extern lv_obj_t * ui_Slider1;
// SCREEN: ui_ecrandespre
void ui_ecrandespre_screen_init(void);
void ui_event_ecrandespre(lv_event_t * e);
extern lv_obj_t * ui_ecrandespre;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_ecranalerte
void ui_ecranalerte_screen_init(void);
extern lv_obj_t * ui_ecranalerte;
extern lv_obj_t * ui_Textalerta;
// SCREEN: ui_ecranbluetooth
void ui_ecranbluetooth_screen_init(void);
extern lv_obj_t * ui_ecranbluetooth;
extern lv_obj_t * ui_numedispozitiv;
extern lv_obj_t * ui_dorestesaseconecteze;
extern lv_obj_t * ui_refuza;
extern lv_obj_t * ui_refuzal;
extern lv_obj_t * ui_accepta;
extern lv_obj_t * ui_acceptal;
// SCREEN: ui_calibraremagscreen
void ui_calibraremagscreen_screen_init(void);
void ui_event_calibraremagscreen(lv_event_t * e);
extern lv_obj_t * ui_calibraremagscreen;
void ui_event_butoncal(lv_event_t * e);
extern lv_obj_t * ui_butoncal;
extern lv_obj_t * ui_textcalibrare;
extern lv_obj_t * ui_textecalibrare;
extern lv_obj_t * ui_textmag;
extern lv_obj_t * ui_textmag1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_634488199);    // assets\31633211-min.png
LV_IMG_DECLARE(ui_img_53009338);    // assets\inima-removebg-preview (1)-min.png
LV_IMG_DECLARE(ui_img_distanta_png);    // assets\distanta.png
LV_IMG_DECLARE(ui_img_1191119266);    // assets\istockphoto-1283581310-170667a-removebg-preview-min-min.png
LV_IMG_DECLARE(ui_img_1673018674);    // assets\fitness_calories-burn-512-min-min.png
LV_IMG_DECLARE(ui_img_1955478482);    // assets\marire_gaura-min.png
LV_IMG_DECLARE(ui_img_1717721989);    // assets\original_facut_dial_2-min-min.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
